title: Luis Loor Maspons - CV
description: CV profesional de Luis Enrique Loor Maspons
baseurl: "/cv-luisloor"
url: "https://leloor.github.io"

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
